name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        echo "APPPASSWORD=${{ secrets.APPPASSWORD }}" >> .env
        echo "APPEMAIL=${{ secrets.APPEMAIL }}" >> .env
        echo "KAFKA_BROKER=${{ secrets.KAFKA_BROKER }}" >> .env

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hosp-connect-notification-svc:latest

    # Tag and Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker tag hosp-connect-notification-svc:latest ${{ secrets.DOCKER_USERNAME }}/hosp-connect-notification-svc:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/hosp-connect-notification-svc:latest

        
